import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Strip from "../components/shared/Strip";
import Header from "../components/shared/Header";
import Footer from "../components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Strip />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
